// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: changeSet.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "changeSet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace xxxDoc {

namespace {

const ::google::protobuf::Descriptor* NSRange_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NSRange_reflection_ = NULL;
const ::google::protobuf::Descriptor* Operation_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Operation_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Operation_State_descriptor_ = NULL;
const ::google::protobuf::Descriptor* ChangeSet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ChangeSet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_changeSet_2eproto() {
  protobuf_AddDesc_changeSet_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "changeSet.proto");
  GOOGLE_CHECK(file != NULL);
  NSRange_descriptor_ = file->message_type(0);
  static const int NSRange_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NSRange, location_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NSRange, length_),
  };
  NSRange_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NSRange_descriptor_,
      NSRange::default_instance_,
      NSRange_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NSRange, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NSRange, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NSRange));
  Operation_descriptor_ = file->message_type(1);
  static const int Operation_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, range_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, originalstring_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, replacestring_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, operationid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, participantid_),
  };
  Operation_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Operation_descriptor_,
      Operation::default_instance_,
      Operation_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Operation, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Operation));
  Operation_State_descriptor_ = Operation_descriptor_->enum_type(0);
  ChangeSet_descriptor_ = file->message_type(2);
  static const int ChangeSet_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChangeSet, startoperationid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChangeSet, cursorlocation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChangeSet, operations_),
  };
  ChangeSet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ChangeSet_descriptor_,
      ChangeSet::default_instance_,
      ChangeSet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChangeSet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ChangeSet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ChangeSet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_changeSet_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NSRange_descriptor_, &NSRange::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Operation_descriptor_, &Operation::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ChangeSet_descriptor_, &ChangeSet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_changeSet_2eproto() {
  delete NSRange::default_instance_;
  delete NSRange_reflection_;
  delete Operation::default_instance_;
  delete Operation_reflection_;
  delete ChangeSet::default_instance_;
  delete ChangeSet_reflection_;
}

void protobuf_AddDesc_changeSet_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017changeSet.proto\022\006xxxDoc\"+\n\007NSRange\022\020\n\010"
    "location\030\001 \001(\003\022\016\n\006length\030\002 \001(\003\"\342\001\n\tOpera"
    "tion\022\036\n\005range\030\001 \001(\0132\017.xxxDoc.NSRange\022\026\n\016"
    "originalString\030\002 \001(\t\022\025\n\rreplaceString\030\003 "
    "\001(\t\022&\n\005state\030\004 \001(\0162\027.xxxDoc.Operation.St"
    "ate\022\023\n\013operationID\030\005 \001(\003\022\025\n\rparticipantI"
    "D\030\006 \001(\003\"2\n\005State\022\t\n\005LOCAL\020\000\022\010\n\004SEND\020\001\022\n\n"
    "\006GLOBAL\020\002\022\010\n\004UNDO\020\003\"d\n\tChangeSet\022\030\n\020star"
    "tOperationID\030\001 \001(\003\022\026\n\016cursorLocation\030\002 \001"
    "(\003\022%\n\noperations\030\003 \003(\0132\021.xxxDoc.Operatio"
    "n", 401);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "changeSet.proto", &protobuf_RegisterTypes);
  NSRange::default_instance_ = new NSRange();
  Operation::default_instance_ = new Operation();
  ChangeSet::default_instance_ = new ChangeSet();
  NSRange::default_instance_->InitAsDefaultInstance();
  Operation::default_instance_->InitAsDefaultInstance();
  ChangeSet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_changeSet_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_changeSet_2eproto {
  StaticDescriptorInitializer_changeSet_2eproto() {
    protobuf_AddDesc_changeSet_2eproto();
  }
} static_descriptor_initializer_changeSet_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int NSRange::kLocationFieldNumber;
const int NSRange::kLengthFieldNumber;
#endif  // !_MSC_VER

NSRange::NSRange()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NSRange::InitAsDefaultInstance() {
}

NSRange::NSRange(const NSRange& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NSRange::SharedCtor() {
  _cached_size_ = 0;
  location_ = GOOGLE_LONGLONG(0);
  length_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NSRange::~NSRange() {
  SharedDtor();
}

void NSRange::SharedDtor() {
  if (this != default_instance_) {
  }
}

void NSRange::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NSRange::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NSRange_descriptor_;
}

const NSRange& NSRange::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_changeSet_2eproto();
  return *default_instance_;
}

NSRange* NSRange::default_instance_ = NULL;

NSRange* NSRange::New() const {
  return new NSRange;
}

void NSRange::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    location_ = GOOGLE_LONGLONG(0);
    length_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NSRange::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 location = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &location_)));
          set_has_location();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_length;
        break;
      }

      // optional int64 length = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_length:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &length_)));
          set_has_length();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NSRange::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int64 location = 1;
  if (has_location()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->location(), output);
  }

  // optional int64 length = 2;
  if (has_length()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->length(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NSRange::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int64 location = 1;
  if (has_location()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->location(), target);
  }

  // optional int64 length = 2;
  if (has_length()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->length(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NSRange::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 location = 1;
    if (has_location()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->location());
    }

    // optional int64 length = 2;
    if (has_length()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->length());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NSRange::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NSRange* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NSRange*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NSRange::MergeFrom(const NSRange& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_location()) {
      set_location(from.location());
    }
    if (from.has_length()) {
      set_length(from.length());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NSRange::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NSRange::CopyFrom(const NSRange& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NSRange::IsInitialized() const {

  return true;
}

void NSRange::Swap(NSRange* other) {
  if (other != this) {
    std::swap(location_, other->location_);
    std::swap(length_, other->length_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NSRange::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NSRange_descriptor_;
  metadata.reflection = NSRange_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* Operation_State_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Operation_State_descriptor_;
}
bool Operation_State_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Operation_State Operation::LOCAL;
const Operation_State Operation::SEND;
const Operation_State Operation::GLOBAL;
const Operation_State Operation::UNDO;
const Operation_State Operation::State_MIN;
const Operation_State Operation::State_MAX;
const int Operation::State_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Operation::kRangeFieldNumber;
const int Operation::kOriginalStringFieldNumber;
const int Operation::kReplaceStringFieldNumber;
const int Operation::kStateFieldNumber;
const int Operation::kOperationIDFieldNumber;
const int Operation::kParticipantIDFieldNumber;
#endif  // !_MSC_VER

Operation::Operation()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Operation::InitAsDefaultInstance() {
  range_ = const_cast< ::xxxDoc::NSRange*>(&::xxxDoc::NSRange::default_instance());
}

Operation::Operation(const Operation& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Operation::SharedCtor() {
  _cached_size_ = 0;
  range_ = NULL;
  originalstring_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  replacestring_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  state_ = 0;
  operationid_ = GOOGLE_LONGLONG(0);
  participantid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Operation::~Operation() {
  SharedDtor();
}

void Operation::SharedDtor() {
  if (originalstring_ != &::google::protobuf::internal::kEmptyString) {
    delete originalstring_;
  }
  if (replacestring_ != &::google::protobuf::internal::kEmptyString) {
    delete replacestring_;
  }
  if (this != default_instance_) {
    delete range_;
  }
}

void Operation::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Operation::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Operation_descriptor_;
}

const Operation& Operation::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_changeSet_2eproto();
  return *default_instance_;
}

Operation* Operation::default_instance_ = NULL;

Operation* Operation::New() const {
  return new Operation;
}

void Operation::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_range()) {
      if (range_ != NULL) range_->::xxxDoc::NSRange::Clear();
    }
    if (has_originalstring()) {
      if (originalstring_ != &::google::protobuf::internal::kEmptyString) {
        originalstring_->clear();
      }
    }
    if (has_replacestring()) {
      if (replacestring_ != &::google::protobuf::internal::kEmptyString) {
        replacestring_->clear();
      }
    }
    state_ = 0;
    operationid_ = GOOGLE_LONGLONG(0);
    participantid_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Operation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .xxxDoc.NSRange range = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_range()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_originalString;
        break;
      }

      // optional string originalString = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_originalString:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_originalstring()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->originalstring().data(), this->originalstring().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_replaceString;
        break;
      }

      // optional string replaceString = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_replaceString:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_replacestring()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->replacestring().data(), this->replacestring().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_state;
        break;
      }

      // optional .xxxDoc.Operation.State state = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_state:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::xxxDoc::Operation_State_IsValid(value)) {
            set_state(static_cast< ::xxxDoc::Operation_State >(value));
          } else {
            mutable_unknown_fields()->AddVarint(4, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_operationID;
        break;
      }

      // optional int64 operationID = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_operationID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &operationid_)));
          set_has_operationid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_participantID;
        break;
      }

      // optional int64 participantID = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_participantID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &participantid_)));
          set_has_participantid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Operation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .xxxDoc.NSRange range = 1;
  if (has_range()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->range(), output);
  }

  // optional string originalString = 2;
  if (has_originalstring()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originalstring().data(), this->originalstring().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->originalstring(), output);
  }

  // optional string replaceString = 3;
  if (has_replacestring()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->replacestring().data(), this->replacestring().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->replacestring(), output);
  }

  // optional .xxxDoc.Operation.State state = 4;
  if (has_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->state(), output);
  }

  // optional int64 operationID = 5;
  if (has_operationid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->operationid(), output);
  }

  // optional int64 participantID = 6;
  if (has_participantid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->participantid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Operation::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .xxxDoc.NSRange range = 1;
  if (has_range()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->range(), target);
  }

  // optional string originalString = 2;
  if (has_originalstring()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->originalstring().data(), this->originalstring().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->originalstring(), target);
  }

  // optional string replaceString = 3;
  if (has_replacestring()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->replacestring().data(), this->replacestring().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->replacestring(), target);
  }

  // optional .xxxDoc.Operation.State state = 4;
  if (has_state()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->state(), target);
  }

  // optional int64 operationID = 5;
  if (has_operationid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->operationid(), target);
  }

  // optional int64 participantID = 6;
  if (has_participantid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->participantid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Operation::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .xxxDoc.NSRange range = 1;
    if (has_range()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->range());
    }

    // optional string originalString = 2;
    if (has_originalstring()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->originalstring());
    }

    // optional string replaceString = 3;
    if (has_replacestring()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->replacestring());
    }

    // optional .xxxDoc.Operation.State state = 4;
    if (has_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
    }

    // optional int64 operationID = 5;
    if (has_operationid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->operationid());
    }

    // optional int64 participantID = 6;
    if (has_participantid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->participantid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Operation::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Operation* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Operation*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Operation::MergeFrom(const Operation& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_range()) {
      mutable_range()->::xxxDoc::NSRange::MergeFrom(from.range());
    }
    if (from.has_originalstring()) {
      set_originalstring(from.originalstring());
    }
    if (from.has_replacestring()) {
      set_replacestring(from.replacestring());
    }
    if (from.has_state()) {
      set_state(from.state());
    }
    if (from.has_operationid()) {
      set_operationid(from.operationid());
    }
    if (from.has_participantid()) {
      set_participantid(from.participantid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Operation::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Operation::CopyFrom(const Operation& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Operation::IsInitialized() const {

  return true;
}

void Operation::Swap(Operation* other) {
  if (other != this) {
    std::swap(range_, other->range_);
    std::swap(originalstring_, other->originalstring_);
    std::swap(replacestring_, other->replacestring_);
    std::swap(state_, other->state_);
    std::swap(operationid_, other->operationid_);
    std::swap(participantid_, other->participantid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Operation::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Operation_descriptor_;
  metadata.reflection = Operation_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ChangeSet::kStartOperationIDFieldNumber;
const int ChangeSet::kCursorLocationFieldNumber;
const int ChangeSet::kOperationsFieldNumber;
#endif  // !_MSC_VER

ChangeSet::ChangeSet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ChangeSet::InitAsDefaultInstance() {
}

ChangeSet::ChangeSet(const ChangeSet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ChangeSet::SharedCtor() {
  _cached_size_ = 0;
  startoperationid_ = GOOGLE_LONGLONG(0);
  cursorlocation_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ChangeSet::~ChangeSet() {
  SharedDtor();
}

void ChangeSet::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ChangeSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChangeSet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ChangeSet_descriptor_;
}

const ChangeSet& ChangeSet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_changeSet_2eproto();
  return *default_instance_;
}

ChangeSet* ChangeSet::default_instance_ = NULL;

ChangeSet* ChangeSet::New() const {
  return new ChangeSet;
}

void ChangeSet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    startoperationid_ = GOOGLE_LONGLONG(0);
    cursorlocation_ = GOOGLE_LONGLONG(0);
  }
  operations_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ChangeSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 startOperationID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &startoperationid_)));
          set_has_startoperationid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_cursorLocation;
        break;
      }

      // optional int64 cursorLocation = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cursorLocation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &cursorlocation_)));
          set_has_cursorlocation();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_operations;
        break;
      }

      // repeated .xxxDoc.Operation operations = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_operations:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_operations()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_operations;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ChangeSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int64 startOperationID = 1;
  if (has_startoperationid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->startoperationid(), output);
  }

  // optional int64 cursorLocation = 2;
  if (has_cursorlocation()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->cursorlocation(), output);
  }

  // repeated .xxxDoc.Operation operations = 3;
  for (int i = 0; i < this->operations_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->operations(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ChangeSet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int64 startOperationID = 1;
  if (has_startoperationid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->startoperationid(), target);
  }

  // optional int64 cursorLocation = 2;
  if (has_cursorlocation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->cursorlocation(), target);
  }

  // repeated .xxxDoc.Operation operations = 3;
  for (int i = 0; i < this->operations_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->operations(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ChangeSet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 startOperationID = 1;
    if (has_startoperationid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->startoperationid());
    }

    // optional int64 cursorLocation = 2;
    if (has_cursorlocation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->cursorlocation());
    }

  }
  // repeated .xxxDoc.Operation operations = 3;
  total_size += 1 * this->operations_size();
  for (int i = 0; i < this->operations_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->operations(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChangeSet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ChangeSet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ChangeSet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ChangeSet::MergeFrom(const ChangeSet& from) {
  GOOGLE_CHECK_NE(&from, this);
  operations_.MergeFrom(from.operations_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_startoperationid()) {
      set_startoperationid(from.startoperationid());
    }
    if (from.has_cursorlocation()) {
      set_cursorlocation(from.cursorlocation());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ChangeSet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChangeSet::CopyFrom(const ChangeSet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChangeSet::IsInitialized() const {

  return true;
}

void ChangeSet::Swap(ChangeSet* other) {
  if (other != this) {
    std::swap(startoperationid_, other->startoperationid_);
    std::swap(cursorlocation_, other->cursorlocation_);
    operations_.Swap(&other->operations_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ChangeSet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ChangeSet_descriptor_;
  metadata.reflection = ChangeSet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace xxxDoc

// @@protoc_insertion_point(global_scope)
